name: Create pull request for updated datasheets
on:
  push:
    branches:
      - 'autoupdate-datasheets'
jobs:
  update-datasheets:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          title: Auto-update datasheets
          branch: autoupdate-datasheets

